export const ROUTES = {
  home: "/",
  search: "/search",
  saved: "/saved",
  review: "/review",
  dashboard: "/dashboard",
  dashboardInquiries: "/dashboard/inquiries",
  dashboardBookings: "/dashboard/bookings",
  dashboardListings: "/dashboard/listings",
  dashboardCalendar: "/dashboard/calendar",
  dashboardWithdrawals: "/dashboard/withdrawals",
  dashboardFeedback: "/dashboard/feedback",
  dashboardPayments: "/dashboard/payments",
  dashboardDemand: "/dashboard/demand",
  newListing: "/dashboard/listings/new",
  terms: "/terms",
  privacy: "/privacy",
  adminHome: "/admin",
  adminUsers: "/admin/users",
  adminBookings: "/admin/bookings",
  adminPayments: "/admin/payments",
  adminHosts: "/admin/hosts",
  adminListings: "/admin/listings",
  adminWithdrawals: "/admin/withdrawals",
  adminDisputes: "/admin/disputes",
  adminFeedback: "/admin/feedback",
  adminDemand: "/admin/demand",
  adminNotifications: "/admin/notifications",
  adminDestinations: "/admin/destinations",
  adminInquiries: "/admin/inquiries",
  adminEvents: "/admin/events",
  adminAnalytics: "/admin/analytics",
  adminUser: (id: string) => `/admin/users/${id}`,
  property: (slug: string) => `/property/${slug}`,
  reserve: (id: string) => `/reserve/${id}`,
  booking: (token: string) => `/booking/${token}`,
} as const;

export const USER_ROUTES = [
  ROUTES.saved,
  ROUTES.dashboard,
  ROUTES.dashboardBookings,
  ROUTES.dashboardListings,
  ROUTES.dashboardCalendar,
  ROUTES.dashboardWithdrawals,
  ROUTES.dashboardFeedback,
] as const;

export const ADMIN_ROUTES = [
  ROUTES.adminHome,
  ROUTES.adminUsers,
  ROUTES.adminBookings,
  ROUTES.adminPayments,
  ROUTES.adminHosts,
  ROUTES.adminListings,
  ROUTES.adminWithdrawals,
  ROUTES.adminDisputes,
  ROUTES.adminFeedback,
  ROUTES.adminDemand,
  ROUTES.adminNotifications,
  ROUTES.adminDestinations,
  ROUTES.adminInquiries,
  ROUTES.adminEvents,
  ROUTES.adminAnalytics,
] as const;
